language: ruby
services:
  - docker
script:
  - docker build -t dockerimageorg/lamp-packages:build-${TRAVIS_JOB_NUMBER} .
  - docker run --name lamp-packages -i -t dockerimageorg/lamp-packages:build-${TRAVIS_JOB_NUMBER}
  - docker login -u ${username} -p ${password}
  - docker tag dockerimageorg/lamp-packages:build-${TRAVIS_JOB_NUMBER} dockerimageorg/lamp-packages:build-${TRAVIS_JOB_NUMBER}
  - docker push dockerimageorg/lamp-packages:build-${TRAVIS_JOB_NUMBER}
env:
  - username=a2564011261
notifications:
  email:
    recipients:
      - A2564011261@163.com
    on_success: always # default: change
    on_failure: always # default: always