language: ruby
services:
  - docker
script:
  - docker build -t dockerimageorg/lamp-packages .
  - docker login -u ${username} -p ${password}
  - docker tag dockerimageorg/lamp-packages:build-${TRAVIS_JOB_NUMBER} dockerimageorg/lamp-packages:build-${TRAVIS_JOB_NUMBER}
  - docker push dockerimageorg/lamp-packages:build-${TRAVIS_JOB_NUMBER}
env:
  - username=a2564011261